# Generated by Django 4.0.1 on 2022-06-02 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_alter_movie_duration_alter_movie_movie_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='description',
            field=models.TextField(max_length=350, verbose_name='Film açıklaması'),
        ),
    ]
