# Generated by Django 4.0.1 on 2022-06-11 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_alter_movie_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='support_image_one',
            field=models.CharField(max_length=100,verbose_name='destekleyici resim 1'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='support_image_two',
            field=models.CharField(max_length=100,verbose_name='destekleyici resim 1'),
        ),
    ]
