# Generated by Django 4.0.1 on 2022-06-11 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_alter_movie_support_image_one_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='support_image_one',
            field=models.CharField(max_length=100, verbose_name='destekleyici resim 1'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='support_image_two',
            field=models.CharField(max_length=100, verbose_name='destekleyici resim 2'),
        ),
    ]
