# Generated by Django 4.0.1 on 2022-06-11 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0005_alter_movie_support_image_one_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='support_image_one',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='support_image_two',
        ),
    ]
